creating single state data class for each screen
ahmedelshaikh20/TodoApp pull request #6
Opened 2024-01-26 21:49 UTC by ahmedelshaikh20

2024-01-29 18:52 UTC, thisAAY requested changes
I like this, I would also suggest experimenting with a `BaseViewModel` that contains some of the logic of the states and events, this is not a must tho

2024-01-29 18:52 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/ui/screens/signinscreen/SignInScreen.kt
> +    Headline("Welcome Back", "")
Use string resources

2024-01-29 18:52 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/ui/screens/signinscreen/SignInScreenState.kt
> +  var userSignInInfo : SignInModel = SignInModel("",""),
If we are using states as UI models we should avoid using domain information here, flatten this class so UserInfoModel info should be in the state as classes, and please don't specify default values here

2024-01-29 18:52 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/ui/screens/signupscreen/SignUpScreenState.kt
> +  var userRegistrationInfo: RegistrationModel = RegistrationModel("", "", ""),
Same here

2024-01-29 18:52 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/ui/screens/splashscreen/SplashScreenState.kt
> +  val currentUserName : String?=null
Don't specify initial values here, let the ViewModel do it

2024-01-29 18:52 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/viewmodel/SignInViewModel.kt
> +  var signInScreenState by mutableStateOf(SignInScreenState())
I know using states here works, but In my opinion it couples the ViewModel with the UI too much that you have to use compose, also using MutableStateFlow here gives you more functionality

2024-01-29 18:52 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/viewmodel/SignInViewModel.kt
> +  var signInScreenState by mutableStateOf(SignInScreenState())
You can name it just `state` you are already inside `SingInViewModel` so it's known which state is this no need to duplicate it
```suggestion
  var state by mutableStateOf(SignInScreenState())
```

2024-01-29 18:52 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/viewmodel/SignInViewModel.kt
> +  val getCurrentUserUseCase: GetCurrentUserUseCase
As we are overriding the invoke operator and using classes as it's functions, you can remove useCase from the end of variables names
```suggestion
  val signIn: SignInUseCase,
  val getCurrentUser: GetCurrentUserUseCase
```

2024-01-29 18:52 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/viewmodel/SignInViewModel.kt
>      when (signInUIEvent) {
I would rename this
```suggestion
    when (event) {
```

2024-01-30 13:09 UTC, ahmedelshaikh20 commented on app/src/main/java/com/example/todoapp/ui/screens/signinscreen/SignInScreenState.kt
> +  var userSignInInfo : SignInModel = SignInModel("",""),
msh fahem

2024-01-31 16:55 UTC, thisAAY requested changes
I really like what you have done with the ViewModel, using Events and States is really cool, Good work 👍 

I still have some concerns but major changes

2024-01-31 16:55 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/ui/screens/homescreen/HomeScreen.kt
> +fun NotesSection(homeViewModel: HomeViewModel) {
Don't pass the viewmodel, make the component provide a callback function for the specific events and implement them in the HomeScreen and use the ViewModel there, Component should be agnostic of how the events should called

2024-01-31 16:55 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/ui/screens/homescreen/HomeScreen.kt
> +          }
Just for your info, you can ignore this or not but you can do it this way,  kotlin supports functional programming so functions can be passed as parameters/variables 😉
```suggestion
          onValueChanged = onTitleChanged
```

2024-01-31 16:55 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/ui/screens/homescreen/HomeScreen.kt
> +          ButtonComponent("Save", modifier = Modifier.padding(10.dp), onClick = {
String resources

2024-01-31 16:55 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/ui/screens/homescreen/HomeScreen.kt
> +            text = "Daily Tasks",
String resources

2024-01-31 16:55 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/ui/screens/homescreen/HomeScreen.kt
> +              color = Color(0xCC000000),
Can't we use Colors.black?

2024-01-31 16:55 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/viewmodel/HomeViewModel.kt
> +   var state by mutableStateOf(HomeScreenState(""))
Why we have curruntUser if we already have a common state like `state`
And please make state a mutable flow it adds more functionality and then you can in compose call `collectAsState`

2024-01-31 16:55 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/viewmodel/SignInViewModel.kt
> +  var state by mutableStateOf(SignInScreenState("", "", "" , false))
Same here, and named params for the SignInScreenState

2024-01-31 16:55 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/viewmodel/SignUpViewModel.kt
>    }
I'm not quite sure about this, wouldn't it better if we show an error message instead of throwing an error? what do you think

2024-01-31 17:02 UTC, thisAAY commented on app/src/main/java/com/example/todoapp/ui/screens/homescreen/HomeScreen.kt
> +              color = Color(0xCC000000),
Okay I noticed you changed the alpha value

2024-01-31 18:21 UTC, ahmedelshaikh20 commented on app/src/main/java/com/example/todoapp/viewmodel/SignUpViewModel.kt
>    }
Of Course

2024-01-31 18:25 UTC, ahmedelshaikh20 commented on app/src/main/java/com/example/todoapp/viewmodel/SignUpViewModel.kt
>    }
But later remind me

2024-01-31 18:25 UTC, ahmedelshaikh20 commented on app/src/main/java/com/example/todoapp/viewmodel/SignUpViewModel.kt
>    }
remind me later please

2024-03-03 19:38 UTC, merged